[package]
name = "link-backend"
version = "0.1.0"
authors = ["esukmean"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "*"
lazy_static = "*"
parking_lot = "*"
rand = "*"